idf_component_register(
    SRCS
        "ui_theme.cpp"
        "ui_app.cpp"
        "render_shared.cpp"
        "render_home.cpp"
        "render_market.cpp"
        "render_weather.cpp"
        "render_indoor.cpp"
        "render_setup.cpp"
        "render_ota.cpp"
        "ui_strings.cpp"
        "settings_menu.cpp"
        "ui_fonts.cpp"
        "fonts/rlcd_cjk_14.c"
        "fonts/rlcd_cjk_20.c"
        "fonts/rlcd_cjk_28.c"
    INCLUDE_DIRS
        "include"
    REQUIRES
        app_core
        board_rlcd
        lvgl__lvgl
)
