idf_component_register(
    SRCS
        "ota.cpp"
        "ota_image.cpp"
        "ota_prefix.cpp"
        "ota_quiesce.cpp"
        "ota_session.cpp"
        "ota_pull.cpp"
        "ota_version.cpp"
        "ota_release.cpp"
        "ota_confirm.cpp"
    INCLUDE_DIRS
        "include"
    REQUIRES
        app_core
        app_update
    PRIV_REQUIRES
        esp_partition
        esp_http_client
        esp-tls
        mbedtls
        json
)
