idf_component_register(
    SRCS
        "display_port.cpp"
        "lvgl_port.cpp"
        "board_buttons.cpp"
        "battery.cpp"
        "board_i2c.cpp"
        "shtc3.cpp"
    INCLUDE_DIRS
        "include"
    PRIV_REQUIRES
        driver
        esp_lcd
        esp_timer
        esp_hw_support
        heap
        spi_flash
        esp_adc
        app_core
    REQUIRES
        lvgl__lvgl
)
